### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by smorzhov** [gw0/docker-keras#5]
This docker image not supporting Volta architecture. Can you add CUDA 9?
I have Tesla V100-SXM2-16GB GPU and got the following error trying to use it inside the container
```bash
2018-01-18 15:59:34.504171: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:152] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
```

**Comment by gw0** [comment]
In order to add CUDA 9.0 and 9.1 support, I have refactored the CUDA image based on Debian 9 without any CUDA Driver libraries in order to prevent driver mismatch issues. Now it is necessary to inject them from the host OS.

Please try out the latest version and reopen the issue, if it does not work for you.
